name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up and build with NeutralinoJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install -g @neutralinojs/neu
      - run: neu build --release

      - name: Check dist folder
        run: |
          pwd
          ls -la
          ls -R dist/

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: varh-app-linux
          if-no-files-found: error
          path: |
            ./dist/varh-app/varh-app-linux_arm64
            ./dist/varh-app/varh-app-linux_x64
            ./dist/varh-app/varh-app-linux_armhf
            ./dist/varh-app/resources.neu

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: varh-app-windows
          path: |
            ./dist/varh-app/varh-app-windows_x64.exe
            ./dist/varh-app/resources.neu

      - name: Upload MacOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: varh-app-macos
          path: |
            ./dist/varh-app/varh-app-mac_x64
            ./dist/varh-app/varh-app-mac_arm64
            ./dist/varh-app/varh-app-mac_universal
            ./dist/varh-app/resources.neu

